# version: '3.8'
# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: database_white_label
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#   mongo:
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME:
#       MONGO_INITDB_ROOT_PASSWORD:
#     ports:
#       - '27017:27017'
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   postgres_data:
#   mongo_data:
